name: Test
on:
  push:
    branches: [develop]
  pull_request:
    branches: [master, develop]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

    - name: Use Node.js
      uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
      with:
        node-version-file: '.nvmrc'

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8.15.9
        run_install: true

    - name: Type check
      run: pnpm type-check

    - name: Lint
      run: pnpm lint

    - name: Test
      run: pnpm test
